# gotty-kubernetes-deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotty
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gotty
  template:
    metadata:
      labels:
        app: gotty
    spec:
      containers:
        - name: gotty
          image: yaronpr/gotty
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: gotty-public-ip
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: gotty
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: web